FORMAT: 1A
HOST: http://api.wcp.vps321.xiag.ch/

# Swisscom web customer portal, mortgage component
API documentation for **Swisscom WCP Mortgage** application.

# Group CSR

Customer Support Representatives

## csr [/financing/csr/{portfolioId}]

### Get schema [OPTIONS]

+ Response 200 (application/schema+json)

    + Header

            Link: <http://api.wcp.vps321.xiag.ch/schema/financing/csr/{portfolioId}>; rel="canonical", <http://api.wcp.vps321.xiag.ch/financing/csr/34231>; rel="self"

    + Body

{
        "GET": {
                "type": "object",
                "properties": {
                        "csr": {
                                "title": "CSR",
                                "description": "Customer Support Representative object",
                                "type": "object",
                                "properties": {
                                        "id": {
                                                "title": "Id",
                                                "description": "CSR identifier",
                                                "type": [
                                                        "string",
                                                        "number"
                                                ]
                                        },
                                        "firstName": {
                                                "title": "First name",
                                                "description": "Customer first name",
                                                "type": "string"
                                        },
                                        "lastName": {
                                                "title": "Last name",
                                                "description": "Customer last name",
                                                "type": "string"
                                        },
                                        "phoneNumber": {
                                                "title": "Phone number",
                                                "description": "Customer phone number",
                                                "type": "string"
                                        },
                                        "faxNumber": {
                                                "title": "Fax number",
                                                "description": "Customer fax number",
                                                "type": "string"
                                        },
                                        "imageURI": {
                                                "title": "Image URI",
                                                "description": "Customer photo",
                                                "type": "string"
                                        }
                                },
                                "required": [
                                        "id",
                                        "firstName",
                                        "lastName",
                                        "phoneNumber",
                                        "faxNumber",
                                        "imageURI"
                                ],
                                "additionalProperties": false
                        }
                },
                "required": [],
                "additionalProperties": false,
                "$schema": "http://json-schema.org/draft-04/schema#"
        },
        "POST": {
                "type": "object",
                "properties": {
                        "success": {
                                "title": "Success",
                                "description": "",
                                "type": "boolean"
                        }
                },
                "required": [],
                "additionalProperties": false,
                "$schema": "http://json-schema.org/draft-04/schema#"
        }
}

### Get CSR [GET]

+ Parameters

    + portfolioId (optional,string, `34231`) ... Portfolio identifier

Return customer support representatives by porfolio identifier

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/csr)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/csr/34231>; rel="self"

    + Body

{
    "response": {
        "csr": {
            "id": "1",
            "firstName": "Thomas",
            "lastName": "Schibler",
            "phoneNumber": "058 800 67 02",
            "faxNumber": "058 800 67 01",
            "imageURI": "//www.szkb.ch/images/default-source/mitarbeiterfotos/48864678216909.jpg"
        }
    }
}

### Send CSR request [POST]

Send request for customer support representatives

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/csr)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/csr>; rel="self"

    + Body

{
    "response": {
        "success": true
    }
}

# Group Portfolio

Portfolios collection

## portfolio [/financing/portfolio]

### Get schema [OPTIONS]

+ Response 200 (application/schema+json)

    + Header

            Link: <http://api.wcp.vps321.xiag.ch/schema/financing/portfolio>; rel="canonical", <http://api.wcp.vps321.xiag.ch/financing/portfolio>; rel="self"

    + Body

{
        "GET": {
                "type": "object",
                "properties": {
                        "portfolio": {
                                "title": "Portfolio",
                                "description": "Portfolio object",
                                "type": "object",
                                "properties": {
                                        "customerId": {
                                                "title": "Customer id",
                                                "description": "Customer identifier",
                                                "type": [
                                                        "string",
                                                        "number"
                                                ]
                                        },
                                        "creditAccount": {
                                                "title": "Credit account",
                                                "description": "Credit account",
                                                "type": "string"
                                        },
                                        "owner": {
                                                "title": "Owner",
                                                "description": "Owner name",
                                                "type": "string"
                                        },
                                        "productId": {
                                                "title": "Product id",
                                                "description": "Product identifier",
                                                "type": [
                                                        "string",
                                                        "number"
                                                ]
                                        },
                                        "rate": {
                                                "title": "Rate",
                                                "description": "Portfolio rate",
                                                "type": [
                                                        "string",
                                                        "number"
                                                ]
                                        },
                                        "currency": {
                                                "title": "Currency",
                                                "description": "ISO 4217 Currency Code",
                                                "type": "string",
                                                "format": "iso4217",
                                                "pattern": "^[A-Z]{3}$"
                                        },
                                        "limit": {
                                                "title": "Limit",
                                                "description": "Credit limit",
                                                "type": "number"
                                        },
                                        "balance": {
                                                "title": "Balance",
                                                "description": "Current balance",
                                                "type": "number"
                                        }
                                },
                                "required": [
                                        "customerId",
                                        "creditAccount",
                                        "owner",
                                        "productId",
                                        "rate",
                                        "currency",
                                        "limit",
                                        "balance"
                                ],
                                "additionalProperties": false
                        }
                },
                "required": [],
                "additionalProperties": false,
                "$schema": "http://json-schema.org/draft-04/schema#"
        }
}

### Get portfolio [GET]

Return portfolio of current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/portfolio)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/portfolio>; rel="self"

    + Body

{
    "response": {
        "portfolio": {
            "customerId": "1318410-27",
            "creditAccount": "456373-3042",
            "owner": "Grätzer-Inderbitzin M. und S.",
            "productId": "100",
            "rate": "multiple",
            "currency": "CHF",
            "limit": 746000,
            "balance": -576000
        }
    }
}

# Group Mortgage

Managing **Mortgage** objects

## mortgage [/financing/mortgage]

### Get schema [OPTIONS]

+ Response 200 (application/schema+json)

    + Header

            Link: <http://api.wcp.vps321.xiag.ch/schema/financing/mortgage>; rel="canonical", <http://api.wcp.vps321.xiag.ch/financing/mortgage>; rel="self"

    + Body

{
        "GET": {
                "type": "object",
                "properties": {
                        "mortgages": {
                                "title": "Mortgages",
                                "description": "Array of mortgages",
                                "type": "array",
                                "items": {
                                        "title": "Mortgage",
                                        "description": "Mortgage object available for customer",
                                        "type": "object",
                                        "properties": {
                                                "id": {
                                                        "title": "Id",
                                                        "description": "Mortgage identifier",
                                                        "type": [
                                                                "string",
                                                                "number"
                                                        ]
                                                },
                                                "productId": {
                                                        "title": "Product id",
                                                        "description": "Product identifier",
                                                        "type": [
                                                                "string",
                                                                "number"
                                                        ]
                                                },
                                                "currency": {
                                                        "title": "Currency",
                                                        "description": "ISO 4217 Currency Code",
                                                        "type": "string",
                                                        "format": "iso4217",
                                                        "pattern": "^[A-Z]{3}$"
                                                },
                                                "limit": {
                                                        "title": "Limit",
                                                        "description": "Total limit",
                                                        "type": "number"
                                                },
                                                "balance": {
                                                        "title": "Balance",
                                                        "description": "Current balance",
                                                        "type": "number"
                                                },
                                                "owner": {
                                                        "title": "Owner",
                                                        "description": "Owner info",
                                                        "type": "object",
                                                        "properties": {
                                                                "id": {
                                                                        "title": "Id",
                                                                        "description": "Owner id",
                                                                        "type": "string"
                                                                },
                                                                "name": {
                                                                        "title": "Name",
                                                                        "description": "Owner name",
                                                                        "type": "string"
                                                                }
                                                        },
                                                        "required": [
                                                                "id",
                                                                "name"
                                                        ]
                                                },
                                                "object": {
                                                        "title": "Object",
                                                        "description": "Object info",
                                                        "type": "object",
                                                        "properties": {
                                                                "name": {
                                                                        "title": "Name",
                                                                        "description": "Object name",
                                                                        "type": "string"
                                                                },
                                                                "additional": {
                                                                        "title": "Additional",
                                                                        "description": "Additional info",
                                                                        "type": "string"
                                                                }
                                                        },
                                                        "required": [
                                                                "name"
                                                        ],
                                                        "additionalProperties": false
                                                },
                                                "products": {
                                                        "title": "Products",
                                                        "description": "Products array",
                                                        "type": "array",
                                                        "items": {
                                                                "title": "Product",
                                                                "description": "",
                                                                "type": "object",
                                                                "properties": {
                                                                        "id": {
                                                                                "title": "Id",
                                                                                "description": "Product identifier",
                                                                                "type": [
                                                                                        "string",
                                                                                        "number"
                                                                                ]
                                                                        },
                                                                        "rate": {
                                                                                "title": "Rate",
                                                                                "description": "Product rate",
                                                                                "type": "string"
                                                                        },
                                                                        "amount": {
                                                                                "title": "Amount",
                                                                                "description": "Credit amount",
                                                                                "type": "number"
                                                                        },
                                                                        "valid": {
                                                                                "title": "Valid",
                                                                                "description": "Credit period",
                                                                                "type": "object",
                                                                                "properties": {
                                                                                        "from": {
                                                                                                "title": "From",
                                                                                                "description": "Credit period start",
                                                                                                "type": "string"
                                                                                        },
                                                                                        "to": {
                                                                                                "title": "To",
                                                                                                "description": "Credit period end",
                                                                                                "type": "string"
                                                                                        }
                                                                                },
                                                                                "required": [
                                                                                        "from",
                                                                                        "to"
                                                                                ],
                                                                                "additionalProperties": false
                                                                        },
                                                                        "offerId": {
                                                                                "type": [
                                                                                        "string",
                                                                                        "number"
                                                                                ]
                                                                        }
                                                                },
                                                                "required": [
                                                                        "id",
                                                                        "rate",
                                                                        "amount",
                                                                        "valid"
                                                                ],
                                                                "additionalProperties": false
                                                        },
                                                        "minItems": 1,
                                                        "uniqueItems": true
                                                }
                                        },
                                        "required": [
                                                "id",
                                                "productId",
                                                "currency",
                                                "limit",
                                                "balance",
                                                "owner",
                                                "object",
                                                "products"
                                        ],
                                        "additionalProperties": false
                                }
                        }
                },
                "required": [],
                "additionalProperties": false,
                "$schema": "http://json-schema.org/draft-04/schema#"
        }
}

### Get mortgages [GET]

Return an array of mortgages available to the customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/mortgage)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/mortgage>; rel="self"

    + Body

{
    "response": {
        "mortgages": [
            {
                "id": "17145",
                "productId": "100",
                "currency": "CHF",
                "limit": 590000,
                "balance": -590000,
                "owner": {
                    "id": "131841-3006",
                    "name": "Hans Muster"
                },
                "object": {
                    "name": "Haus 1",
                    "additional": "Kurzstrasse 22 7770 St.Gallen"
                },
                "products": [
                    {
                        "id": "9010390041",
                        "rate": "2.45",
                        "amount": 590000,
                        "valid": {
                            "from": "2010-04-01",
                            "to": "2015-03-31"
                        },
                        "offerId": "21137"
                    }
                ]
            },
            {
                "id": "17146",
                "productId": "100",
                "currency": "CHF",
                "limit": 990000,
                "balance": -990000,
                "owner": {
                    "id": "131841-4982",
                    "name": "Hans Muster"
                },
                "object": {
                    "name": "Object 2",
                    "additional": "Kurzstrasse 2 1770 St.Gallen"
                },
                "products": [
                    {
                        "id": "9010390041",
                        "rate": "2.45",
                        "amount": 390000,
                        "valid": {
                            "from": "2010-06-02",
                            "to": "2014-01-01"
                        },
                        "offerId": "21973"
                    },
                    {
                        "id": "9010390041",
                        "rate": "2.05",
                        "amount": 300000,
                        "valid": {
                            "from": "2011-07-01",
                            "to": "2015-06-30"
                        },
                        "offerId": "21973"
                    },
                    {
                        "id": "9010390041",
                        "rate": "2.15",
                        "amount": 300000,
                        "valid": {
                            "from": "2011-07-01",
                            "to": "2037-06-30"
                        }
                    }
                ]
            }
        ]
    }
}

## mortgage_configuration [/financing/mortgage_configuration/{mortgageId}]

### Get schema [OPTIONS]

+ Response 200 (application/schema+json)

    + Header

            Link: <http://api.wcp.vps321.xiag.ch/schema/financing/mortgage_configuration/{mortgageId}>; rel="canonical", <http://api.wcp.vps321.xiag.ch/financing/mortgage_configuration/17146>; rel="self"

    + Body

{
        "GET": {
                "type": "object",
                "properties": {
                        "mortgage": {
                                "type": "object",
                                "properties": {
                                        "initial": {
                                                "title": "Initial",
                                                "description": "Initial configuration array",
                                                "type": "array",
                                                "items": {
                                                        "title": "Product",
                                                        "description": "",
                                                        "type": "object",
                                                        "properties": {
                                                                "id": {
                                                                        "title": "Id",
                                                                        "description": "Product identifier",
                                                                        "type": [
                                                                                "string",
                                                                                "number"
                                                                        ]
                                                                },
                                                                "rate": {
                                                                        "title": "Rate",
                                                                        "description": "Product rate",
                                                                        "type": "string"
                                                                },
                                                                "amount": {
                                                                        "title": "Amount",
                                                                        "description": "Credit amount",
                                                                        "type": "number"
                                                                },
                                                                "valid": {
                                                                        "title": "Valid",
                                                                        "description": "Credit period",
                                                                        "type": "object",
                                                                        "properties": {
                                                                                "from": {
                                                                                        "title": "From",
                                                                                        "description": "Credit period start",
                                                                                        "type": "string"
                                                                                },
                                                                                "to": {
                                                                                        "title": "To",
                                                                                        "description": "Credit period end",
                                                                                        "type": "string"
                                                                                }
                                                                        },
                                                                        "required": [
                                                                                "from",
                                                                                "to"
                                                                        ],
                                                                        "additionalProperties": false
                                                                },
                                                                "offerId": {
                                                                        "type": [
                                                                                "string",
                                                                                "number"
                                                                        ]
                                                                }
                                                        },
                                                        "required": [
                                                                "id",
                                                                "rate",
                                                                "amount",
                                                                "valid"
                                                        ],
                                                        "additionalProperties": false
                                                }
                                        }
                                },
                                "required": [
                                        "initial"
                                ]
                        }
                },
                "$schema": "http://json-schema.org/draft-04/schema#"
        },
        "POST": {
                "type": "object",
                "properties": {
                        "success": {
                                "title": "Success",
                                "description": "Success save flag",
                                "type": [
                                        "boolean"
                                ]
                        }
                },
                "required": [
                        "success"
                ],
                "additionalProperties": false,
                "$schema": "http://json-schema.org/draft-04/schema#"
        }
}

### Get mortgage configuration [GET]

+ Parameters

    + mortgageId (required,string, `17146`) ... Mortgage identifier

Return configuration object of mortgage

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/mortgage_configuration)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/mortgage_configuration/17146>; rel="self"

    + Body

{
    "response": {
        "mortgage": {
            "initial": [
                {
                    "id": "9010390041",
                    "rate": "2.45",
                    "amount": 390000,
                    "valid": {
                        "from": "2010-06-02",
                        "to": "2014-01-01"
                    },
                    "offerId": "21973"
                },
                {
                    "id": "9010390041",
                    "rate": "2.05",
                    "amount": 300000,
                    "valid": {
                        "from": "2011-07-01",
                        "to": "2015-06-30"
                    },
                    "offerId": "21973"
                },
                {
                    "id": "9010390041",
                    "rate": "2.15",
                    "amount": 300000,
                    "valid": {
                        "from": "2011-07-01",
                        "to": "2037-06-30"
                    }
                }
            ],
            "configured": {
                "test": 123
            }
        }
    }
}

### Save mortgage configuration [POST]

+ Parameters

    + mortgageId (required,string, `17146`) ... Mortgage identifier
    + configuration (required) ... Mortgage configuration object

Save configuration object of mortgage and return status of success

+ Request (application/json)

{
    "mortgageId": "17146",
    "configuration": {
        "test": 123
    }
}

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/mortgage_configuration)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/mortgage_configuration/17146>; rel="self"

    + Body

{
    "response": {
        "success": true
    }
}

# Group Offer

Offer as a products collection for mortgage part extension

## offer [/financing/offer/{offerId}]

### Get schema [OPTIONS]

+ Response 200 (application/schema+json)

    + Header

            Link: <http://api.wcp.vps321.xiag.ch/schema/financing/offer/{offerId}>; rel="canonical", <http://api.wcp.vps321.xiag.ch/financing/offer/21137>; rel="self"

    + Body

{
        "GET": {
                "type": "object",
                "properties": {
                        "products": {
                                "title": " products",
                                "description": "Array of products",
                                "type": "array",
                                "items": {
                                        "title": "Offer",
                                        "description": "Offer object",
                                        "type": "object",
                                        "properties": {
                                                "id": {
                                                        "title": "Id",
                                                        "description": "Offer idintifier",
                                                        "type": [
                                                                "string",
                                                                "number"
                                                        ]
                                                },
                                                "duration": {
                                                        "title": "Duration",
                                                        "description": "Credit duration",
                                                        "type": "number"
                                                },
                                                "actualMargin": {
                                                        "title": "Actual margin",
                                                        "description": "Actual margin",
                                                        "type": "string"
                                                },
                                                "minimalAmount": {
                                                        "title": "Minimal amount",
                                                        "description": "Minimal amount",
                                                        "type": "number"
                                                }
                                        },
                                        "required": [
                                                "id",
                                                "duration",
                                                "actualMargin",
                                                "minimalAmount"
                                        ],
                                        "additionalProperties": false
                                }
                        }
                },
                "required": [],
                "additionalProperties": false,
                "$schema": "http://json-schema.org/draft-04/schema#"
        }
}

### Get offer products [GET]

+ Parameters

    + offerId (required,string, `21137`) ... Offer identifier for  products

Return array of products by offer identifier

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/offer)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/offer/21137>; rel="self"

    + Body

{
    "response": {
        "products": [
            {
                "id": "9010390041",
                "duration": 2,
                "actualMargin": "3.9996",
                "minimalAmount": 100000
            },
            {
                "id": "9010390041",
                "duration": 3,
                "actualMargin": "3.8996",
                "minimalAmount": 100000
            },
            {
                "id": "9010390041",
                "duration": 4,
                "actualMargin": "3.7996",
                "minimalAmount": 100000
            },
            {
                "id": "9010390041",
                "duration": 5,
                "actualMargin": "3.6996",
                "minimalAmount": 100000
            },
            {
                "id": "9010390041",
                "duration": 6,
                "actualMargin": "3.5996",
                "minimalAmount": 100000
            },
            {
                "id": "9010390041",
                "duration": 7,
                "actualMargin": "3.4996",
                "minimalAmount": 100000
            },
            {
                "id": "9010390041",
                "duration": 8,
                "actualMargin": "3.3996",
                "minimalAmount": 100000
            },
            {
                "id": "9010390041",
                "duration": 9,
                "actualMargin": "3.2996",
                "minimalAmount": 100000
            },
            {
                "id": "9010390041",
                "duration": 10,
                "actualMargin": "3.1996",
                "minimalAmount": 100000
            }
        ]
    }
}

# Group Product

Products collection

## product [/financing/product/{productsIds}]

### Get schema [OPTIONS]

+ Response 200 (application/schema+json)

    + Header

            Link: <http://api.wcp.vps321.xiag.ch/schema/financing/product/{productsIds}>; rel="canonical", <http://api.wcp.vps321.xiag.ch/financing/product/undefined>; rel="self"

    + Body

{
        "GET": {
                "type": "object",
                "properties": {
                        "products": {
                                "title": " Products data",
                                "description": "Array of products data",
                                "type": "array",
                                "items": {
                                        "title": "Product title",
                                        "description": "Product title object",
                                        "type": "object",
                                        "properties": {
                                                "id": {
                                                        "title": "Id",
                                                        "description": "Product identifier",
                                                        "type": [
                                                                "string",
                                                                "number"
                                                        ]
                                                },
                                                "name": {
                                                        "title": "Name",
                                                        "description": "Product name",
                                                        "type": "string"
                                                },
                                                "type": {
                                                        "title": "Type",
                                                        "description": "Product type",
                                                        "type": "string"
                                                }
                                        },
                                        "required": [
                                                "id",
                                                "name",
                                                "type"
                                        ],
                                        "additionalProperties": false
                                }
                        }
                },
                "required": [],
                "additionalProperties": false,
                "$schema": "http://json-schema.org/draft-04/schema#"
        }
}

### Get products data [GET]

+ Parameters

    + productsIds (optional,array, `undefined`) ... Products ids separated by comma

Return array of products data

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/product)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/product/undefined>; rel="self"

    + Body

{
    "response": {
        "products": []
    }
}

# Group Misc

Not grouped services

## current_year [/financing/current_year]

### Get schema [OPTIONS]

+ Response 200 (application/schema+json)

    + Header

            Link: <http://api.wcp.vps321.xiag.ch/schema/financing/current_year>; rel="canonical", <http://api.wcp.vps321.xiag.ch/financing/current_year>; rel="self"

    + Body

{
        "GET": {
                "type": "object",
                "properties": {
                        "year": {
                                "title": "Year",
                                "description": "Current year",
                                "type": [
                                        "number"
                                ]
                        }
                },
                "required": [
                        "year"
                ],
                "additionalProperties": false,
                "$schema": "http://json-schema.org/draft-04/schema#"
        }
}

### Get current year [GET]

Return current year

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/current_year)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/current_year>; rel="self"

    + Body

{
    "response": {
        "year": 2014
    }
}
