FORMAT: 1A
HOST: http://api.wcp.vps321.xiag.ch/

# Swisscom web customer portal, mortgage component
API documentation for **Swisscom WCP Mortgage** application.

# Group getCsrByPortfolioID

undefined

##  [/financing/getCsrByPortfolioID]

### Get schema [OPTIONS]

##  [/financing/getCsrByPortfolioID/{portfolioId}]

### Call service [GET]

+ Parameters

    + portfolioId (optional, string) ... Portfolio identifier

Return mortgage collection available for current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/getCsrByPortfolioID)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/getCsrByPortfolioID>; rel="self"

    + Body

{
        "response": {
                "csr": {
                        "id": "1",
                        "firstName": "Thomas",
                        "lastName": "Schibler",
                        "phoneNumber": "058 800 67 02",
                        "faxNumber": "058 800 67 01",
                        "imageURI": "//www.szkb.ch/images/default-source/mitarbeiterfotos/48864678216909.jpg"
                }
        }
}

# Group sendCsrRequest

undefined

##  [/financing/sendCsrRequest]

### Get schema [OPTIONS]

##  [/financing/sendCsrRequest]

### Call service [GET]

Return mortgage collection available for current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/sendCsrRequest)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/sendCsrRequest>; rel="self"

    + Body

{
        "response": {
                "success": true
        }
}

# Group getPortfolio

undefined

##  [/financing/getPortfolio]

### Get schema [OPTIONS]

##  [/financing/getPortfolio]

### Call service [GET]

Return mortgage collection available for current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/getPortfolio)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/getPortfolio>; rel="self"

    + Body

{
        "response": {
                "portfolio": {
                        "customerId": "1318410-27",
                        "creditAccount": "456373-3042",
                        "owner": "Grätzer-Inderbitzin M. und S.",
                        "productId": "100",
                        "rate": "multiple",
                        "currency": "CHF",
                        "limit": 746000,
                        "balance": -576000
                }
        }
}

# Group getMortgages

undefined

##  [/financing/getMortgages]

### Get schema [OPTIONS]

##  [/financing/getMortgages]

### Call service [GET]

Return mortgage collection available for current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/getMortgages)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/getMortgages>; rel="self"

    + Body

{
        "response": {
                "mortgages": [
                        {
                                "id": "17145",
                                "productId": "100",
                                "currency": "CHF",
                                "limit": 590000,
                                "balance": -590000,
                                "owner": {
                                        "id": "131841-3006",
                                        "name": "Hans Muster"
                                },
                                "object": {
                                        "name": "Haus 1",
                                        "additional": "Kurzstrasse 22 7770 St.Gallen"
                                },
                                "products": [
                                        {
                                                "id": "9010390041",
                                                "rate": "2.45",
                                                "amount": 590000,
                                                "valid": {
                                                        "from": "2010-04-01",
                                                        "to": "2015-03-31"
                                                },
                                                "offerId": "21137"
                                        }
                                ]
                        },
                        {
                                "id": "17146",
                                "productId": "100",
                                "currency": "CHF",
                                "limit": 990000,
                                "balance": -990000,
                                "owner": {
                                        "id": "131841-4982",
                                        "name": "Hans Muster"
                                },
                                "object": {
                                        "name": "Object 2",
                                        "additional": "Kurzstrasse 2 1770 St.Gallen"
                                },
                                "products": [
                                        {
                                                "id": "9010390041",
                                                "rate": "2.45",
                                                "amount": 390000,
                                                "valid": {
                                                        "from": "2010-06-02",
                                                        "to": "2014-01-01"
                                                },
                                                "offerId": "21973"
                                        },
                                        {
                                                "id": "9010390041",
                                                "rate": "2.05",
                                                "amount": 300000,
                                                "valid": {
                                                        "from": "2011-07-01",
                                                        "to": "2015-06-30"
                                                },
                                                "offerId": "21973"
                                        },
                                        {
                                                "id": "9010390041",
                                                "rate": "2.15",
                                                "amount": 300000,
                                                "valid": {
                                                        "from": "2011-07-01",
                                                        "to": "2037-06-30"
                                                }
                                        }
                                ]
                        }
                ]
        }
}

# Group getReplacementProductsByOfferId

undefined

##  [/financing/getReplacementProductsByOfferId]

### Get schema [OPTIONS]

##  [/financing/getReplacementProductsByOfferId/{offerId}]

### Call service [GET]

+ Parameters

    + offerId (required, string) ... 

Return mortgage collection available for current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/getReplacementProductsByOfferId)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/getReplacementProductsByOfferId>; rel="self"

    + Body

{
        "error": "schema mismatch: Missing required property: offerId"
}

# Group getProductsData

undefined

##  [/financing/getProductsData]

### Get schema [OPTIONS]

##  [/financing/getProductsData/{productsIds}]

### Call service [GET]

+ Parameters

    + productIds (required, array) ... Products ids

Return mortgage collection available for current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/getProductsData)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/getProductsData>; rel="self"

    + Body

{
        "error": "schema mismatch: Missing required property: productIds"
}

# Group getMortgageConfiguration

undefined

##  [/financing/getMortgageConfiguration]

### Get schema [OPTIONS]

##  [/financing/getMortgageConfiguration/{mortgageId}]

### Call service [GET]

+ Parameters

    + mortgageId (required, string) ... Mortgage identifier

Return mortgage collection available for current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/getMortgageConfiguration)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/getMortgageConfiguration>; rel="self"

    + Body

{
        "error": "schema mismatch: Missing required property: mortgageId"
}

# Group setMortgageConfiguration

undefined

##  [/financing/setMortgageConfiguration]

### Get schema [OPTIONS]

##  [/financing/setMortgageConfiguration]

### Call service [POST]

+ Parameters

    + mortgageId (required, string) ... Mortgage
    + configuration (required, object) ... 

Return mortgage collection available for current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/setMortgageConfiguration)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/setMortgageConfiguration>; rel="self"

    + Body

{}

# Group getCurrentYear

undefined

##  [/financing/getCurrentYear]

### Get schema [OPTIONS]

##  [/financing/getCurrentYear]

### Call service [GET]

Return mortgage collection available for current customer

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/getCurrentYear)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/getCurrentYear>; rel="self"

    + Body

{
        "response": {
                "year": 2014
        }
}
