FORMAT: 1A
HOST: http://api.wcp.vps321.xiag.ch/

# Swisscom web customer portal, mortgage component
API documentation for **Swisscom WCP Mortgage** application.

# Group Mortgages
Managing **Mortgage** objects

## Mortgages Collection [/financing/mortgage]

### Get Mortgage collection schema [OPTIONS]

+ Response 200 (application/schema+json)

    + Header

            Link: <http://api.wcp.vps321.xiag.ch/schema/financing/mortgage/collection>; rel="canonical", <http://api.wcp.vps321.xiag.ch/financing/mortgage>; rel="self"

    + Body

            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "array",
                "title": "Array of mortgage objects",
                "description": "Mortgage object collection available for customer",
                "items": {
                    "type": "object",
                    "title": "Mortgage",
                    "description": "Mortgage object available for customer",
                    "properties": {
                        "id": {
                            "type": "string",
                            "title": "Id",
                            "description": "Mortgage identifier"
                        },
                        "currency": {
                            "type": "string",
                            "title": "ISO 4217 Currency Code",
                            "format": "iso4217",
                            "pattern": "^[A-Z]{3}$",
                            "description": "Mortgage currency"
                        },
                        "limit": {
                            "type": "number",
                            "minimum": 0,
                            "exclusiveMinimum": true
                            "title": "Mortgage limit"
                        },
                        "balance": {
                            "type": "number",
                            "maximum": 0,
                            "title": "Mortgage balance"
                        },
                        "owner": {
                            "type": "object",
                            "title": "Owner",
                            "description": "Mortgage owner information",
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "title": "Id",
                                    "description": "Mortgage owner identifier"
                                },
                                "name": {
                                    "type": "string",
                                    "title": "Name",
                                    "description": "Mortgage owner name"
                                }
                            },
                            "required": [
                                "id",
                                "name"
                            ]
                        },
                        "object": {
                            "type": "object",
                            "title": "Mortgage object",
                            "description": "Mortgage object information",
                            "properties": {
                                "name": {
                                    "type": "string",
                                    "title": "Name",
                                    "description": "Mortgage object name"
                                },
                                "additional": {
                                    "type": "string",
                                    "title": "Additional data",
                                    "description": "Mortgage object additional data"
                                }
                            },
                            "required": [
                                "name"
                            ]
                        },
                        "products": {
                            "type": "array",
                            "title": "Array of mortgage product",
                            "description": "Current mortgage products configuration",
                            "items": {
                                "type": "object",
                                "title": "Product",
                                "description": "Mortgage product",
                                "properties": {
                                    "id": {
                                        "type": "string",
                                        "title": "Id",
                                        "description": "Product identifier"
                                    },
                                    "rate": {
                                        "type": "string",
                                        "minLength": 1,
                                        "title": "Rate",
                                        "description": "Product rate"
                                    },
                                    "amount": {
                                        "type": "number",
                                        "minimum": 0,
                                        "exclusiveMinimum": true,
                                        "title": "Product amount"
                                    },
                                    "valid": {
                                        "type": "object",
                                        "title": "Valid",
                                        "description": "Product validation interval",
                                        "properties": {
                                            "from": {
                                                "type": "string",
                                                "format": "date",
                                                "title": "From",
                                                "description": "Start interval value"
                                            },
                                            "to": {
                                                "type": "string",
                                                "format": "date",
                                                "title": "To",
                                                "description": "End interval value"
                                            }
                                        },
                                        "required": [
                                            "from",
                                            "to"
                                        ]
                                    },
                                    "offerId": {
                                        "type": "string",
                                        "title": "Offer Id",
                                        "description": "Product configuration offer identifier"
                                    }
                                },
                                "required": [
                                    "id",
                                    "rate",
                                    "amount",
                                    "valid"
                                ]
                            },
                            "minItems": 1,
                            "uniqueItems": true
                        }
                    },
                    "required": [
                        "id",
                        "currency",
                        "limit",
                        "balance",
                        "owner",
                        "object",
                        "products"
                    ]
                },
                "minItems": 1,
                "uniqueItems": true
            }

### List all Mortgages [GET]

Return mortgage collection available for current customer


+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/mortgage/collection)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/mortgage>; rel="self"

    + Body

            [
                {
                    "id": "17145",
                    "currency": "CHF",
                    "limit": 590000,
                    "balance": -590000,
                    "owner": {
                        "id": "131841-3006",
                        "name": "Hans Muster"
                    },
                    "object": {
                        "name": "Haus 1",
                        "additional": "Kurzstrasse 22 7770 St.Gallen"
                    },
                    "products": [
                        {
                            "id": "9010390041",
                            "rate": "2.45",
                            "amount": 590000,
                            "valid": {
                                "from": "2010-04-01",
                                "to": "2015-03-31"
                            },
                            "offerId": "21137"
                        }
                    ]
                },
                {
                    "id": "17146",
                    "currency": "CHF",
                    "limit": 490000,
                    "balance": -490000,
                    "owner": {
                        "id": "131841-4982",
                        "name": "Hans Muster"
                    },
                    "object": {
                        "name": "Object 2",
                        "additional": "Kurzstrasse 2 1770 St.Gallen"
                    },
                    "products": [
                        {
                            "id": "9010390041",
                            "rate": "2.45",
                            "amount": 190000,
                            "valid": {
                                "from": "2010-06-01",
                                "to": "2015-05-31"
                            },
                            "offerId": "21973"
                        },
                        {
                            "id": "9010390041",
                            "rate": "2.05",
                            "amount": 300000,
                            "valid": {
                                "from": "2011-07-01",
                                "to": "2016-06-30"
                            }
                        }
                    ]
                }
            ]

## Offer [/financing/offer/{id}]

+ Parameters

    + id (mandatory, string, `21973`) ... Id of offer to return.

### Get product collection schema [OPTIONS]

+ Response 200 (application/schema+json)

    + Header

            Link: <http://api.wcp.vps321.xiag.ch/schema/financing/offer/item>; rel="canonical", <http://api.wcp.vps321.xiag.ch/financing/offer/21973>; rel="self"

    + Body

            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "array",
                "title": "Array of offer product objects",
                "description": "Offer product object collection",
                "items": {
                    "type": "object",
                    "title": "Product",
                    "description": "Offer product",
                    "properties": {
                        "id": {
                            "type": "string",
                            "title": "Id",
                            "description": "Offered product identifier"
                        },
                        "duration": {
                            "type": "integer",
                            "minimum": 2,
                            "maximum": 10,
                            "title": "Duration",
                            "description": "Offered product duration in years"
                        },
                        "actualMargin": {
                            "type": "string",
                            "minLength": 1,
                            "title": "Rate",
                            "description": "Actual product rate"
                        },
                        "minimalAmount": {
                            "type": "number",
                            "minimum": 0,
                            "exclusiveMinimum": true
                        }
                    },
                    "required": [
                        "id",
                        "duration",
                        "actualMargin",
                        "minimalAmount"
                    ]
                },
                "minItems": 1,
                "uniqueItems": true
            }

### Get single offer as product collection [GET]

Product collection

+ Response 200 (application/json; charset=UTF-8; profile=http://api.wcp.vps321.xiag.ch/schema/financing/offer/item)

    + Header

            Content-Language: en
            Link: <http://api.wcp.vps321.xiag.ch/financing/offer/21973>; rel="self"

    + Body

            [
                {
                    "id": "1",
                    "duration": 2,
                    "actualMargin": "2.9996",
                    "minimalAmount": 100000
                },
                {
                    "id": "1",
                    "duration": 3,
                    "actualMargin": "2.8996",
                    "minimalAmount": 150000
                },
                {
                    "id": "1",
                    "duration": 4,
                    "actualMargin": "2.7996",
                    "minimalAmount": 200000
                },
                {
                    "id": "1",
                    "duration": 5,
                    "actualMargin": "2.6996",
                    "minimalAmount": 250000
                },
                {
                    "id": "1",
                    "duration": 6,
                    "actualMargin": "2.5996",
                    "minimalAmount": 300000
                },
                {
                    "id": "1",
                    "duration": 7,
                    "actualMargin": "2.4996",
                    "minimalAmount": 350000
                },
                {
                    "id": "1",
                    "duration": 8,
                    "actualMargin": "2.3996",
                    "minimalAmount": 400000
                },
                {
                    "id": "1",
                    "duration": 9,
                    "actualMargin": "2.2996",
                    "minimalAmount": 450000
                },
                {
                    "id": "1",
                    "duration": 10,
                    "actualMargin": "2.1996",
                    "minimalAmount": 500000
                }
            ]
